[package]
name = "ghostblood"
version = "0.1.0"

[workspace]
members = ["kernel"]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[build-dependencies]
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }
bootloader = "0.11.4"
